<?php

declare(strict_types=1);

namespace NetBrothers\KostentraegerParser\SgbV\Enum;

/**
 * @author Thilo Ratnaweera <thilo.ratnaweera@netbrothers.de>
 * @copyright © 2025 NetBrothers GmbH.
 * @license All rights reserved.
 */
enum AbrechnungscodeEnum: string
{
	case ALLE_LEISTUNGSARTEN = '00';
	case SONDERSCHLUESSEL = '99';
	case GRUPPENSCHLUESSEL_HILFSMITTELLIEFERANT = '10';
	case APOTHEKE = '11';
	case AUGENOPTIKER = '12';
	case AUGENARZT = '13';
	case HOERGERAETEAKUSTIKER = '14';
	case ORTHOPAEDIEMECHANIKER_BANDAGIST_SANITAETSHAUS = '15';
	case ORTHOPAEDIESCHUHMACHER = '16';
	case ORTHOPAEDE = '17';
	case SANITAETSHAUS_DEPRECATED = '18';
	case SONSTIGER_HILFSMITTELLIEFERANT = '19';
	case GRUPPENSCHLUESSEL_HEILMITTELERBRINGER = '20';
	case MASSEUR_MEDIZINISCHER_BADEBETRIEB = '21';
	case KRANKENGYMNAST_PHYSIOTHERAPEUT = '22';
	case LOGOPAEDE = '23';
	case SPRACHHEILPAEDAGOGE = '24';
	case SONSTIGER_SPRACHTHERAPEUT = '25';
	case ERGOTHERAPEUT = '26';
	case KRANKENHAUS = '27';
	case KURBETRIEB = '28';
	case SONSTIGE_THERAPEUTISCHE_HEILPERSON = '29';
	case GRUPPENSCHLUESSEL_HAEUSLICHE_KRANKENPFLEGE = '30';
	case FREIGEMEINNUETZIGE_ANBIETER = '31';
	case PRIVATGEWERBLICHE_ANBIETER = '32';
	case OEFFENTLICHE_ANBIETER = '33';
	case SONSTIGE_PFLEGEDIENSTE = '34';
	case GRUPPENSCHLUESSEL_KRANKENTRANSPORTLEISTUNGEN = '40';
	case OEFFENTLICHER_TRAEGER = '41';
	case DEUTSCHES_ROTES_KREUZ = '42';
	case ARBEITER_SAMARITER_BUND = '43';
	case JOHANNITER_UNFALL_HILFE = '44';
	case MALTESER_HILFSDIENST = '45';
	case SONSTIGER_LEISTUNGSERBRINGER_BODENGEBUNDENER_TRANSPORTLEISTUNGEN = '46';
	case LEISTUNGSERBRINGER_FLUGRETTUNGS_UND_TRANSPORTLEISTUNGEN = '47';
	case SONSTIGER_LEISTUNGSERBRINGER_KRANKENTRANSPORTLEISTUNGEN = '49';
	case HEBAMME = '50';
	case SONSTIGER_LEISTUNGSERBRINGER_NICHTAERZTLICHE_DIALYSESACHLEISTUNGEN = '55';
	case KURATORIUM_HEIMDIALYSE = '56';
	case PATIENTEN_HEIMVERSORGUNG = '57';
	case BETRIEBSHILFE = '60';
	case LEISTUNGSERBRINGER_REHABILITATIONSSPORT = '61';
	case LEISTUNGSERBRINGER_FUNKTIONSTRAINING = '62';
	case LEISTUNGSERBRINGER_ERGAENZENDE_REHABILITATIONSMASSNAHMEN = '63';
	case SONSTIGE_LEISTUNGSERBRINGER = '65';
	case LEISTUNGSERBRINGER_PRAEVENTIONS_UND_GESUNDHEITSFOERDERUNGSMASSNAHMEN_AMBULANT = '66';
	case AMBULANTES_REHAZENTRUM = '67';
	case SOZIALPAEDIATRISCHE_ZENTREN = '68';
	case SOZIOTHERAPEUTISCHE_LEISTUNGSERBRINGER = '69';
	case PODOLOGEN = '71';
	case LEISTUNGSERBRINGER_ERNAEHRUNGSTHERAPIE_SELTENE_ANGEBORENE_STOFFWECHSELERKRANKUNGEN = '73';
	case LEISTUNGSERBRINGER_ERNAEHRUNGSTHERAPIE_MUKOVISZIDOSE = '74';
	case MED_FUSSPFLEGER = '72';
	case SPEZIALISIERTE_AMBULANTE_PALLIATIVVERSORGUNG = '75';
	case LEISTUNGSERBRINGER_NACH_PAR_132G_SGB_V = '76';
	case LEISTUNGSERBRINGER_MODELLVORHABEN_NACH_PAR_64D_SGB_V = 'B1';
	case GRUPPENSCHLUESSEL_AUSSERKLINISCHE_INTENSIVPFLEGE = 'A0';
	case FREIGEMEINNUETZIGER_ANBIETER_A1 = 'A1';
	case PRIVATGEWERBLICHE_ANBIETER_A2 = 'A2';
	case OEFFENTLICHER_ANBIETER_A3 = 'A3';
	case SONSTIGER_ANBIETER_STATIONAERE_AKI = 'A4';
	case FREIGEMEINNUETZIGER_ANBIETER_A5 = 'A5';
	case PRIVATGEWERBLICHE_ANBIETER_A6 = 'A6';
	case OEFFENTLICHER_ANBIETER_A7 = 'A7';
	case SONSTIGER_ANBIETER = 'A8';
	case GRUPPENSCHLUESSEL_KURZZEITPFLEGE = '90';
	case KURZZEITPFLEGE_PRIVAT_GEWERBLICH = '91';
	case KURZZEITPFLEGE_FREI_GEMEINNUETZIG = '92';
	case KURZZEITPFLEGE_OEFFENTLICH = '93';
	case KURZZEITPFLEGE_SONSTIGE = '94';
}
