<?php

declare(strict_types=1);

namespace NetBrothers\KostentraegerParser\SgbV\Enum;

/**
 * @author Thilo Ratnaweera <thilo.ratnaweera@netbrothers.de>
 * @copyright © 2025 NetBrothers GmbH.
 * @license All rights reserved.
 */
enum KvBezirkEnum: string
{
	case SCHLESWIG_HOLSTEIN = '01';
	case HAMBURG = '02';
	case BREMEN = '03';
	case BEZIRKSSTELLE_AURICH = '06';
	case BEZIRKSSTELLE_BRAUNSCHWEIG = '07';
	case BEZIRKSSTELLE_GOETTINGEN = '08';
	case BEZIRKSSTELLE_HANNOVER = '09';
	case BEZIRKSSTELLE_HILDESHEIM = '10';
	case BEZIRKSSTELLE_LUENEBURG = '11';
	case BEZIRKSSTELLE_OLDENBURG = '12';
	case BEZIRKSSTELLE_OSNABRUECK = '13';
	case BEZIRKSSTELLE_STADE = '14';
	case BEZIRKSSTELLE_VERDEN = '15';
	case BEZIRKSSTELLE_WILHELMSHAVEN = '16';
	case NIEDERSACHSEN = '17';
	case VERWALTUNGSSTELLE_DORTMUND = '18';
	case VERWALTUNGSSTELLE_MUENSTER = '19';
	case WESTFALEN_LIPPE = '20';
	case BEZIRKSSTELLE_AACHEN = '21';
	case BEZIRKSSTELLE_DUESSELDORF = '24';
	case BEZIRKSSTELLE_DUISBURG = '25';
	case BEZIRKSSTELLE_KOELN = '27';
	case BEZIRKSSTELLE_LINKER_NIEDERRHEIN = '28';
	case BEZIRKSSTELLE_RUHR = '31';
	case BEZIRKSSTELLE_BERGISCH_LAND = '37';
	case NORDRHEIN = '38';
	case BEZIRKSSTELLE_DARMSTADT = '39';
	case BEZIRKSSTELLE_FRANKFURT = '40';
	case BEZIRKSSTELLE_GIESSEN = '41';
	case BEZIRKSSTELLE_KASSEL = '42';
	case BEZIRKSSTELLE_LIMBURG = '43';
	case BEZIRKSSTELLE_MARBURG = '44';
	case BEZIRKSSTELLE_WIESBADEN = '45';
	case HESSEN = '46';
	case KOBLENZ = '47';
	case RHEINHESSEN = '48';
	case PFALZ = '49';
	case TRIER = '50';
	case ABRECHNUNGSSTELLE_KARLSRUHE = '52';
	case ABRECHNUNGSSTELLE_MANNHEIM = '53';
	case ABRECHNUNGSSTELLE_PFORTZHEIM = '54';
	case NORDBADEN = '55';
	case ABRECHNUNGSSTELLE_BADEN_BADEN = '56';
	case ABRECHNUNGSSTELLE_FREIBURG = '57';
	case ABRECHNUNGSSTELLE_KONSTANZ = '58';
	case ABRECHNUNGSSTELLE_OFFENBURG = '59';
	case SUEDBADEN = '60';
	case NORDWUERTTEMBERG = '61';
	case SUEDWUERTTEMBERG = '62';
	case BEZIRKSSTELLE_MUENCHEN_STADT_U_LAND = '63';
	case BEZIRKSSTELLE_OBERBAYERN = '64';
	case BEZIRKSSTELLE_OBERFRANKEN = '65';
	case BEZIRKSSTELLE_MITTELFRANKEN = '66';
	case BEZIRKSSTELLE_UNTERFRANKEN = '67';
	case BEZIRKSSTELLE_OBERPFALZ = '68';
	case BEZIRKSSTELLE_NIEDERBAYERN = '69';
	case BEZIRKSSTELLE_SCHWABEN = '70';
	case BAYERNS = '71';
	case BERLIN = '72';
	case SAARLAND = '73';
	case MECKLENBURG_VORPOMMERN = '78';
	case ABRECHNUNGSSTELLE_POTSDAM = '79';
	case ABRECHNUNGSSTELLE_COTTBUS = '80';
	case ABRECHNUNGSSTELLE_FRANKFURT_ODER = '81';
	case BRANDENBURG = '83';
	case ABRECHNUNGSSTELLE_MAGDEBURG = '85';
	case ABRECHNUNGSSTELLE_HALLE = '86';
	case ABRECHNUNGSSTELLE_DESSAU = '87';
	case SACHSEN_ANHALT = '88';
	case ABRECHNUNGSSTELLE_ERFURT = '89';
	case ABRECHNUNGSSTELLE_GERA = '90';
	case ABRECHNUNGSSTELLE_SUHL = '91';
	case THUERINGEN = '93';
	case BEZIRKSSTELLE_CHEMNITZ = '94';
	case BEZIRKSSTELLE_DRESDEN = '95';
	case BEZIRKSSTELLE_LEIPZIG = '96';
	case SACHSEN = '98';
}
